---
application:
  name: "mooviz"
  project: "mylion-app"
  organization: "mylion"
databases:
- type: "MYSQL"
  name: "mooviz"
  version: "5.7"
routers:
- name: "main-mooviz"
  routes:
  - application_name: "mooviz"
    paths:
    - "/*"
