---
application:
  name: "mylion-app"
  project: "mylion"
  organization: "QoveryCommunity"
  storage:
  - name: "upload"
    size: "100"
    type: "fast_ssd"
    mount_point: "/images/upload"
  - name: "uploads"
    size: "90"
    type: "fast_ssd"
    mount_point: "/videos/uploads"
databases:
- type: "MYSQL"
  name: "mooviz"
  version: "5.7"
routers:
- name: "main-mylion-app"
  routes:
  - application_name: "mylion-app"
    paths:
    - "/*"
